services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
    networks:
      - app_network

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server1
    networks:
      - app_network
    environment:
      - SERVER_ID=Server-1
    ports:
      - "8001:8000"
    develop:
      watch:
        - path: ./server
          action: rebuild

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server2
    networks:
      - app_network
    environment:
      - SERVER_ID=Server-2
    ports:
      - "8002:8000"
    develop:
      watch:
        - path: ./server
          action: rebuild

networks:
  app_network:
    driver: bridge
